    name: Build Go Project

    on:
      push:
        branches:
          - main
      pull_request:
        branches:
          - main

    jobs:
      build:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout repository
            uses: actions/checkout@v4

          - name: Set up Go
            uses: actions/setup-go@v5
            with:
              go-version: '1.22' # Specify your desired Go version

          - name: Build Go application
            run: go build -o hello-app .

          - name: Run Go application (optional)
            run: ./hello-app
